### ISSUE TITLE
Staff-Hacker information update

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#21] opened 2018-07-31 03:00 UTC
As a staff member, I want to scan hackers' QR codes in order to update their information.

**Comment by pierreTklein** [comment] 2018-09-11 21:17
On the front-end, this would work in this way:
- scan QR code
- translate QR code to Hacker ID
- make POST request to update Hacker detail for status

**Comment by pierreTklein** [comment] 2018-11-01 02:34
there should be a route that has restricted access to updating a hacker:
List of things it should do: 
* Check in a user

**Comment by pierreTklein** [comment] 2018-11-01 02:34
Actually, this is a duplicate of #14

**Closed by pierreTklein** 2018-11-01 02:34 UTC
Labels: Admin Facing, Pri 2
